spring.application.name=demo
spring.datasource.url=jdbc:postgresql://dpg-d71tlh5m5p6s73a1bte0-a.oregon-postgres.render.com:5432/mydatabase_ihry
spring.datasource.username=mydatabase_ihry_user
spring.datasource.password=btgjdb5vT0uAaDzQbrvy14nW2TKEosFa
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8081}
jwt.secret=${JWT_SECRET:ThisIsADevOnlyJwtSecretKeyThatIsAtLeast32Bytes}
jwt.expiration-millis=${JWT_EXPIRATION_MILLIS:86400000}